# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'https://tomajask.github.io'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Tomasz Jaśkiewicz'
  email: jaskiewicztomasz@gmail.com
  twitter_username: tomjaskiewicz
  facebook_username: jaskiewicztomasz
  github_username:  tomajask
  linkedin_username:  tomaszjaskiewicz

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Handling Reading
encoding:     'utf-8'
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
